var json = [{
  id: 1,
  headshot: "https://i.imgur.com/gzuG5IP.jpg",
  fullname: "Davia DeNisco",
  github: "https://github.com/daviadenisco",
  linkedin: "https://www.linkedin.com/in/davia-denisco-2889317",
  email: "mailto:davia@daviadenisco.com",
  personalsite: "http://www.daviadenisco.com/",
  capstonelink: "https://galvanizestudentgallery.herokuapp.com/",
  capstonedesc: "For my capstone project, I created this app that you're using right now. The idea came about when I saw the opportunity to streamline the communications and guest experience for the capstone showcase by making a student gallery for users to preview and browse projects before, during, and after the event.",
  q1project: "http://www.daviadenisco.com/snake/",
  q2project: "https://techtionary.herokuapp.com/",
  q3project: "https://g72bestwebdevs.herokuapp.com/",
  bio: "I'm a software engineer based in New York City, where I was born and raised. After graduating from Drew University with a double major in Fine Art and History, I worked in event management for The Estée Lauder Companies, and then for The Open Society Foundations. I'm currently looking for a full-time position as a software engineer. In the meantime, I'm working on several freelance projects and will soon be teaching an intro to HTML, CSS, and JavaScript class. In my free time, I like to rescue cats, kiss wolves, and hike across volcanoes.",
  funfact: "I once found a message in a bottle on a beach.",
  funpic: "https://imgur.com/FSdo8WG",
  requestresume: "mailto:davia@daviadenisco.com?subject=Resume request&body=Hi, I saw your capstone profile and would like to view your resume. Could you please send it to me? Thanks!",
  extraspace1: "https://i.imgur.com/92u4M1G.png",
  extraspace2: "https://i.imgur.com/TCTPMoq.jpg",
  extraspace3: "https://i.imgur.com/YH5KVaG.png",
  extraspace4: "https://i.imgur.com/YH5KVaG.png",
  extraspace5: ""
}, {
  id: 2,
  headshot: "https://i.imgur.com/XnRCSeQ.jpg",
  fullname: "David Nyman",
  github: "https://github.com/davidnymanmusic",
  linkedin: "https://www.linkedin.com/in/david-nyman-a65a8a17/",
  email: "mailto:davenyman@gmail.com",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "Serenity Now is a meditation and focus app built in React Native with streaming music player featuring original compositions written for the project. Includes Google Analytics for event tracking and media storage with AWS S3.",
  q1project: "http://davidnymanmusic.github.io/white-noise",
  q2project: "http://dogeat.herokuapp.com/",
  q3project: "http://ring-signal.herokuapp.com/",
  bio: "Starting with a background in music composition for film and commercials, I am excited to shift gears into the world of web development. As someone who likes to be behind the scenes, I have enjoyed learning about the internet's inner workings. I am currently seeking full-time employment as a software engineer. Though music is my domain (pun intended), I am open to new opportunities in a variety of fields.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:davenyman@gmail.com?subject=Resume request&body=Hi, I saw your capstone profile and would like to view your resume. Could you please send it to me? Thanks!",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 3,
  headshot: "https://i.imgur.com/Biu7y7z.png",
  fullname: "Don Tamayo",
  github: "https://github.com/webbydon29",
  linkedin: "https://www.linkedin.com/in/don-aldrich-tamayo-2b0204132/",
  email: "mailto:amazingmardon@gmail.com",
  personalsite: "https://resume-viewer2018.herokuapp.com/",
  capstonelink: "",
  capstonedesc: "For my capstone project, I made the most useful app the world will ever know. It's the most convenient and the best designed app ever. Not only is it free to download, your bank account will be credited $1 every time you open the app.",
  q1project: "https://webbydon29.github.io/Q1_cars_2nd/index.html",
  q2project: "https://nba-apps-2018.herokuapp.com/",
  q3project: "https://nba-apps-2018.herokuapp.com/",
  bio: "",
  funfact: "",
  funpic: "",
  requestresume: "mailto:amazingmardon@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 4,
  headshot: "https://i.imgur.com/yecnx3Z.jpg",
  fullname: "Gonpo Lama",
  github: "https://github.com/gonpolama",
  linkedin: "https://www.linkedin.com/in/gonpo-lama-68b0a840/",
  email: "mailto:gonpolama@gmail.com",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "My capstone project is, rather ironically given my sedentary nature, a workout app. I became interested in building this application primarily because I wanted to work with APIs, and include a dynamic texting feature. The application is made with React.js on the front-end, and Node.js on the back.",
  q1project: "https://gonpolama.github.io/anagrams/",
  q2project: "https://q3project.herokuapp.com/",
  q3project: "https://q3project.herokuapp.com/",
  bio: "My name is Gonpo Lama and I am part of the g72 web development cohort at Galvanize. I am Tibetan by ethnicity, but also spent a lot of time growing up in Nepal, India, and Taiwan before finally ending up in the United States, where I got a degree from Williams College. I became interested in programming after working as a grant writer and technical recruiter; coding appealed to my passion for solving difficult problems, love of languages, and meticulous nature.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:gonpolama@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 5,
  headshot: "https://i.imgur.com/uHu09GK.jpg",
  fullname: "Jon Aquarone",
  github: "https://github.com/Jontronics",
  linkedin: "https://www.linkedin.com/in/jonathan-aquarone-73085189/",
  email: "mailto:j.aquarone@gmail.com",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "For my capstone project, I made the most useful app the world will ever know. It's the most convenient and the best designed app ever. Not only is it free to download, your bank account will be credited $1 every time you open the app.",
  q1project: "https://i.imgur.com/u6J3Vhn.jpg",
  q2project: "https://i.imgur.com/u6J3Vhn.jpg",
  q3project: "https://i.imgur.com/u6J3Vhn.jpg",
  bio: "",
  funfact: "",
  funpic: "",
  requestresume: "mailto:j.aquarone@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 6,
  headshot: "https://i.imgur.com/lC1D5iQ.jpg",
  fullname: "Kyle Treman",
  github: "https://github.com/jkyletreman",
  linkedin: "https://www.linkedin.com/in/jkyletreman/",
  email: "mailto:jkt290@nyu.edu",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "For my capstone project, I made the most useful app the world will ever know. It's the most convenient and the best designed app ever. Not only is it free to download, your bank account will be credited $1 every time you open the app.",
  q1project: "https://html-platformer-jungle-jumper.firebaseapp.com/",
  q2project: "https://stark-citadel-36057.herokuapp.com/recipes/",
  q3project: "https://flash-app-react-galvanize.herokuapp.com/",
  bio: "",
  funfact: "",
  funpic: "",
  requestresume: "mailto:jkt290@nyu.edu",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 7,
  headshot: "https://i.imgur.com/U5PYID3.jpg",
  fullname: "Mike Allen",
  github: "https://github.com/mikevocalz",
  linkedin: "https://www.linkedin.com/in/michael-allen-3b538429/",
  email: "mailto:mikevocalz@aol.com",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "For my capstone project, I made the most useful app the world will ever know. It's the most convenient and the best designed app ever. Not only is it free to download, your bank account will be credited $1 every time you open the app.",
  q1project: "https://i.imgur.com/u6J3Vhn.jpg",
  q2project: "https://i.imgur.com/u6J3Vhn.jpg",
  q3project: "https://i.imgur.com/u6J3Vhn.jpg",
  bio: "",
  funfact: "",
  funpic: "",
  requestresume: "mailto:mikevocalz@aol.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 8,
  headshot: "https://i.imgur.com/qLEciTm.jpg",
  fullname: "Mona Temchin",
  github: "https://github.com/MonaTem",
  linkedin: "https://www.linkedin.com/in/monatemchin/",
  email: "mailto:monatemchin@gmail.com",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "For my capstone project, I made Fabia’s Fabulous Fairytales. On the website, the user chooses from various characters (Bear, Witch, etc.) and picks a happy or sad ending. The computer generates a fairytale from these choices and reads it out loud.",
  q1project: "https://monatem.github.io/q1-project-mvp/",
  q2project: "https://still-ravine-87799.herokuapp.com/",
  q3project: "https://still-ravine-87799.herokuapp.com/",
  bio: "I’m a very creative person who enjoys using my imagination to create and build. In my former life, I was a hard working mainframe programmer. So although the Javascript and React ecosystem is very different from the mainframe, I already know how to think and solve problems in a software engineering way. I enjoy using both sides of my brain!! When I’m not coding, I can be found reading (mostly fantasy and science fiction), taking spin classes, eating vegetarian food, studying holistic healing, writing, gaming, or cuddling with my cat, Yogi. Also, I love all things purple. I’m looking forward to contributing to a business where I’m a good fit for the company culture.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:monatemchin@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 9,
  headshot: "https://i.imgur.com/4lYyS6B.jpg",
  fullname: "Riley Green",
  github: "https://github.com/rgreenviiiv",
  linkedin: "https://www.linkedin.com/in/riley-green-aaaa2463/",
  email: "mailto:rileygreenviiiv@gmail.com",
  personalsite: "",
  capstonelink: "",
  capstonedesc: "For my capstone project, I made the most useful app the world will ever know. It's the most convenient and the best designed app ever. Not only is it free to download, your bank account will be credited $1 every time you open the app.",
  q1project: "http://diligent-dog.surge.sh/",
  q2project: "http://q2-wine-pairing.herokuapp.com/",
  q3project: "http://q2-wine-pairing.herokuapp.com/",
  bio: "",
  funfact: "",
  funpic: "",
  requestresume: "mailto:rileygreenviiiv@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}]

module.exports.json = json;
