var json = [{
  id: 1,
  headshot: "https://i.imgur.com/gzuG5IP.jpg",
  fullname: "Davia DeNisco",
  github: "https://github.com/daviadenisco",
  linkedin: "https://www.linkedin.com/in/davia-denisco-2889317",
  email: "mailto:davia@daviadenisco.com",
  personalsite: "http://www.daviadenisco.com/",
  capstonelink: "https://galvanizestudentgallery.herokuapp.com/",
  capstonedesc: "For my capstone project, I created this Galvanize Student Gallery app that you're using right now. The idea came about when I saw the opportunity to enhance the capstone showcase communications and guest experience by creating a portal for users to learn about Galvanize's newest developers, and to preview and browse projects before, during, and after the event.",
  q1project: "http://www.daviadenisco.com/snake/",
  q2project: "https://techtionary.herokuapp.com/",
  q3project: "https://g72bestwebdevs.herokuapp.com/",
  bio: "I'm a software engineer based in New York City. Before pursuing coding, I worked in event management for The Estée Lauder Companies and for The Open Society Foundations. I'm currently looking for a full-time position as a software engineer. In the meantime, I'm working on several freelance projects and will soon be teaching an intro to HTML, CSS, and JavaScript class. In my free time, I like to rescue cats, kiss wolves, and hike across volcanoes.",
  funfact: "I once found a message in a bottle on a beach.",
  funpic: "https://imgur.com/FSdo8WG",
  requestresume: "mailto:davia@daviadenisco.com?subject=Resume request&body=Hi, I saw your capstone profile and would like to view your resume. Could you please send it to me? Thanks!",
  extraspace1: "https://i.imgur.com/92u4M1G.png",
  extraspace2: "https://i.imgur.com/TCTPMoq.jpg",
  extraspace3: "https://i.imgur.com/YH5KVaG.png",
  extraspace4: "https://i.imgur.com/YH5KVaG.png",
  extraspace5: ""
}, {
  id: 2,
  headshot: "https://i.imgur.com/XnRCSeQ.jpg",
  fullname: "David Nyman",
  github: "https://github.com/davidnymanmusic",
  linkedin: "https://www.linkedin.com/in/david-nyman-a65a8a17/",
  email: "mailto:davenyman@gmail.com",
  personalsite: "http://www.davidnymanmusic.com/",
  capstonelink: "http://serenity-now-capstone.herokuapp.com/",
  capstonedesc: "Serenity Now is a meditation and focus app built in React Native with streaming music player featuring original compositions written for the project. Includes Google Analytics for event tracking and media storage with AWS S3.",
  q1project: "http://davidnymanmusic.github.io/white-noise",
  q2project: "http://dogeat.herokuapp.com/",
  q3project: "http://ring-signal.herokuapp.com/",
  bio: "Starting with a background in music composition for film and commercials, I am excited to shift gears into the world of web development. As someone who likes to be behind the scenes, I have enjoyed learning about the internet's inner workings. I am currently seeking full-time employment as a software engineer. Though music is my domain (pun intended), I am open to new opportunities in a variety of fields.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:davenyman@gmail.com?subject=Resume request&body=Hi, I saw your capstone profile and would like to view your resume. Could you please send it to me? Thanks!",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 3,
  headshot: "https://i.imgur.com/Biu7y7z.png",
  fullname: "Don Tamayo",
  github: "https://github.com/dontamayo",
  linkedin: "https://www.linkedin.com/in/don-aldrich-tamayo-2b0204132/",
  email: "mailto:amazingmardon@gmail.com",
  personalsite: "http://caringhandmaidens.com/sample-page/",
  capstonelink: "https://carmania2.herokuapp.com/",
  capstonedesc: "I'm created an app for Car Enthusiasts, it includes latest movies, news, blogs, sell  your cars and many more. I used reactJS, node modules NPM's ( npm react-router-dom react-fontawesome react-simple-sidenav react-slick axios json-server –dev) and firebase database, authenticaton, Heroku and many more.",
  q1project: "https://dontamayo.github.io/Q1_cars_2nd/index.html",
  q2project: "https://nba-apps-2018.herokuapp.com/",
  q3project: "https://nba-apps-2018.herokuapp.com/",
  bio: "My name is Don Tamayo,  Seventh-day Adventist  Church Pastor in Philippines and New Jersey SDA Conference. (2009- present). I started Web Developing through affiliate marketing, curiosity on how to make money online. From then I started creating websites, monetizing, optimizing using different platforms to compete with other popular websites. My eagerness to grow my passion became stronger until I decided to formally train myself and enrolled in Galvanize which I learned unlimited load of knowledge. I’m actively working freelance contract projects in New Jersey also I’m available to work full time position as a Full-Stack Engineer and join the workforce of Creative Mind in the the World of technology. ",
  funfact: "",
  funpic: "",
  requestresume: "mailto:amazingmardon@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 4,
  headshot: "https://i.imgur.com/yecnx3Z.jpg",
  fullname: "Gonpo Lama",
  github: "https://github.com/gonpolama",
  linkedin: "https://www.linkedin.com/in/gonpo-lama-68b0a840/",
  email: "mailto:gonpolama@gmail.com",
  personalsite: "http://contactstudentdirectly.surge.sh/",
  capstonelink: "http://contactstudentdirectly.surge.sh/",
  capstonedesc: "My capstone project is, rather ironically given my sedentary nature, a workout app. I became interested in building this application primarily because I wanted to work with APIs, and include a dynamic texting feature. The application is made with React.js on the front-end, and Node.js on the back.",
  q1project: "https://gonpolama.github.io/anagrams/",
  q2project: "https://q3project.herokuapp.com/",
  q3project: "https://q3project.herokuapp.com/",
  bio: "My name is Gonpo Lama and I am part of the g72 web development cohort at Galvanize. I am Tibetan by ethnicity, but also spent a lot of time growing up in Nepal, India, and Taiwan before finally ending up in the United States, where I got a degree from Williams College. I became interested in programming after working as a grant writer and technical recruiter; coding appealed to my passion for solving difficult problems, love of languages, and meticulous nature.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:gonpolama@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 5,
  headshot: "https://i.imgur.com/uHu09GK.jpg",
  fullname: "Jon Aquarone",
  github: "https://github.com/Jontronics",
  linkedin: "https://www.linkedin.com/in/jonathan-aquarone-73085189/",
  email: "mailto:j.aquarone@gmail.com",
  personalsite: "http://contactstudentdirectly.surge.sh/",
  capstonelink: "http://contactstudentdirectly.surge.sh/",
  capstonedesc: "My capstone project helps pro skaters share secrete skate spots in an exclusive network.",
  q1project: "https://leadscare-2a474.firebaseapp.com/",
  q2project: "https://github.com/Jontronics/project-q2",
  q3project: "https://github.com/Jontronics/react-google-map",
  bio: "Hello my name is Jonathan and I've got chops in all phases of design, prototyping and development process. I collaborate with clients and peers to nurture and transform ideas into well thought out design specs. Afer all, that's where the majority of amazing user experiences start. I sketch and wireframe interfaces focusing on content structure, intuitive UI patterns and simple interactions. I'm a minimalist who truly believes that less is more. To validate product features, I quickly prototype and have potential users test the product using Product Management methodologies. I can build full stack web applications to get your product out the door and into users hands as fast as possible.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:j.aquarone@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 6,
  headshot: "https://i.imgur.com/lC1D5iQ.jpg",
  fullname: "Kyle Treman",
  github: "https://github.com/jkyletreman",
  linkedin: "https://www.linkedin.com/in/jkyletreman/",
  email: "mailto:jkt290@nyu.edu",
  personalsite: "http://contactstudentdirectly.surge.sh/",
  capstonelink: "http://contactstudentdirectly.surge.sh/",
  capstonedesc: "We all have to eat, but that simple task can become tedious and time consuming, especially during the week. Feed Me, is a meal planner app uses that premise to make planning, scheduling and buying a weeks worth of meals easy. Users are able to select their meals, add them to a day of the week, view their shopping list and receive that list texted to them. Feed Me built with React, React Router, NodeJS, PostgreSQL, Electron, CircleCi and Ant Design.",
  q1project: "https://html-platformer-jungle-jumper.firebaseapp.com/",
  q2project: "https://stark-citadel-36057.herokuapp.com/recipes/",
  q3project: "https://flash-app-react-galvanize.herokuapp.com/",
  bio: "I became interested in software development while working with start-ups. I saw the ways in which well designed technology magnified a businesses success and improved the lives of its customers. I’ve always been interested in solving problems, especially problems that required me to build something or where I could help others, so web development became a natural fit. In addition to coding, I spend time organizing, leading or speaking at community events, be it for algorithms or philosophy.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:jkt290@nyu.edu",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 7,
  headshot: "https://i.imgur.com/U5PYID3.jpg",
  fullname: "Mike Allen",
  github: "https://github.com/mikevocalz",
  linkedin: "https://www.linkedin.com/in/michael-allen-3b538429/",
  email: "mailto:mikewallen@protonmail.com",
  personalsite: "http://contactstudentdirectly.surge.sh/",
  capstonelink: "http://contactstudentdirectly.surge.sh/",
  capstonedesc: "Please contact Mike directly for information on his capstone project.",
  q1project: "http://contactstudentdirectly.surge.sh/",
  q2project: "http://contactstudentdirectly.surge.sh/",
  q3project: "https://drive.google.com/file/d/1qitXVXkYvb82re_wGKS9DsFmhJJX3q61/view",
  bio: "I am a Web Developer who has over 10 plus years experience in UI/UX design. I worked in the Health Care industry as a graphic designer and data entry specialist. Outside of the design world i have worked as a background vocalist for several artist as well as a musical theater actor in local touring companies. I am currently enrolled in Galvanize’s Full Stack Web Developer Immersive Program. As a student here, i’m keeping up with todays design trends and technology. I am learning industry standards, clean code base and creating visually appealing applications. My goal is to to take all the amazing skills I’ve learned from Galvanize and put those skills to work at a start-up and a company that utilizes current design standards and technology.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:mikevocalz@aol.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 8,
  headshot: "https://i.imgur.com/qLEciTm.jpg",
  fullname: "Mona Temchin",
  github: "https://github.com/MonaTem",
  linkedin: "https://www.linkedin.com/in/monatemchin/",
  email: "mailto:monatemchin@gmail.com",
  personalsite: "http://contactstudentdirectly.surge.sh/",
  capstonelink: "https://fabias-fabulous-fairytales.herokuapp.com/",
  capstonedesc: "Fabia’s Fabulous Fairytales is a website where the user chooses from various characters (Bear, Witch, etc.) and picks a happy or sad ending. The computer generates a fairytale from these choices and reads it out loud.",
  q1project: "https://monatem.github.io/q1-project-mvp/",
  q2project: "https://still-ravine-87799.herokuapp.com/",
  q3project: "https://still-ravine-87799.herokuapp.com/",
  bio: "I’m a very creative person who enjoys using my imagination to create and build. In my former life, I was a hard working mainframe programmer. So although the Javascript and React ecosystem is very different from the mainframe, I already know how to think and solve problems in a software engineering way. I enjoy using both sides of my brain!! When I’m not coding, I can be found reading (mostly fantasy and science fiction), taking spin classes, eating vegetarian food, studying holistic healing, writing, gaming, or cuddling with my cat, Yogi. Also, I love all things purple. I’m looking forward to contributing to a business where I’m a good fit for the company culture.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:monatemchin@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}, {
  id: 9,
  headshot: "https://i.imgur.com/4lYyS6B.jpg",
  fullname: "Riley Green",
  github: "https://github.com/rgreenviiiv",
  linkedin: "https://www.linkedin.com/in/riley-green-aaaa2463/",
  email: "mailto:rileygreenviiiv@gmail.com",
  personalsite: "http://contactstudentdirectly.surge.sh/",
  capstonelink: "http://contactstudentdirectly.surge.sh/",
  capstonedesc: "Please contact Riley directly for information on his capstone project.",
  q1project: "http://diligent-dog.surge.sh/",
  q2project: "http://q2-wine-pairing.herokuapp.com/",
  q3project: "http://q2-wine-pairing.herokuapp.com/",
  bio: "Please contact Riley directly to learn more.",
  funfact: "",
  funpic: "",
  requestresume: "mailto:rileygreenviiiv@gmail.com",
  extraspace1: "",
  extraspace2: "",
  extraspace3: "",
  extraspace4: "",
  extraspace5: ""
}]

module.exports.json = json;
